### ISSUE TITLE
Leaflet map doesn't load completely

### ISSUE THREAD

**Issue by zaqmarlon** [isaacmsl/happy#2]
When map page is linked by index page (Server Side Rendered),  Leaflet map doesn't load completely.

![image](https://user-images.githubusercontent.com/31693006/95810657-e0987a80-0ce7-11eb-9c87-48410101fa5a.png)

I'm using dynamic component to load map on client side - because it doen'st work on SSR rendering (ReferenceError: window is not defined)

Currently component:

https://github.com/isaacmsl/happy/blob/4c6bc46414a9bdd604a4d13db33a483229319527/src/components/LeafletMapDynamic.tsx#L1-L7

**Comment by MateusAbdala** [comment]
#3

**Comment by zaqmarlon** [comment]
@MateusAbdala , see PR #4, i used `react-leaflet-universal` package. Thank you for helping!

**Comment by MateusAbdala** [comment]
@isaacmsl could you label my PR #3 **hacktoberfest-accepted**?

thank you and nice project by the way!
